# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function for concentration steps (refinement) in rlg
#' @name rlg_c2
#' @param x Rcpp::NumericMatrix, The input data.
#' @param d Rcpp::NumericVector, A numeric vector of length equal to the number 
#'  of clusters to be detected. 
#'  Each component of vector \code{d} indicates the intrinsic dimension of the affine subspace 
#'  where observations on that cluster are going to be clustered. All the elements 
#'  of vector \code{d} should be smaller than the problem dimension minus 1.
#' @param cluster Rcpp::NumericVector  A numeric vector of size \code{n} containing 
#'  the cluster assignment for each observation. Cluster names are integer numbers 
NULL

#' Internal function for concentration steps (initializations) in rlg
#' @name rlg_c1
#' @param x Rcpp::NumericMatrix, The input data.
#' @param d Rcpp::NumericVector, A numeric vector of length equal to the number 
#'  of clusters to be detected. 
#'  Each component of vector \code{d} indicates the intrinsic dimension of the affine subspace 
#'  where observations on that cluster are going to be clustered. All the elements 
#'  of vector \code{d} should be smaller than the problem dimension minus 1.
#' @param alpha double, The proportion of observations to be trimmed.
#' @param niter1 int, The number of concentration steps to be performed for the 
#' nstart initializations. 
#' @export
rlg_c1 <- function(x, d, alpha = 0.05, niter1 = 3L) {
    .Call(`_robClus_rlg_c1`, x, d, alpha, niter1)
}

#' @param alpha double, The proportion of observations to be trimmed.
#' @param niter2 int, The maximum number of concentration steps to be performed for 
#'  the \code{nkeep} solutions kept for further iteration. The concentration steps 
#'  are stopped, whenever two consecutive steps lead to the same data partition. 
#' @export
rlg_c2 <- function(x, d, cluster, alpha = 0.05, niter2 = 20L) {
    .Call(`_robClus_rlg_c2`, x, d, cluster, alpha, niter2)
}

#' Internal function for concentration steps (initializations) in tclust2
#' @name tclust_c1
#' @param x Rcpp::NumericMatrix, The input data.
#' @param k The number of clusters initially searched for.
#' @param alpha double, The proportion of observations to be trimmed.
#' @param restrC Restriction type (0 for restriction on eigenvalues or determinant)
#' @param deterC Restriction on determinants (true or false)
#' @param restr_fact The constant \code{restr_fact >= 1} constrains the allowed 
#'  differences among group scatters in terms of eigenvalues ratio. Larger values 
#'  imply larger differences of group scatters, a value of 1 specifies the 
#'  strongest restriction.
#' @param cshape Shape constraint
#' @param niter1 int, The number of concentration steps to be performed for the 
#'     nstart initializations. 
#' @param opt Define the target function to be optimized. A classification likelihood 
#'  target function is considered if \code{opt="HARD"} and a mixture classification 
#'  likelihood if \code{opt="MIXT"}.
#' @param equal_weights A logical value, specifying whether equal cluster weights 
#'  shall be considered in the concentration and assignment steps.
#' @param zero_tol The zero tolerance used. By default set to 1e-16.
NULL

tclust_c1 <- function(x, k, alpha = 0.05, restrC = 0L, deterC = FALSE, restr_fact = 12, cshape = 1e10, niter1 = 3L, opt = "HARD", equal_weights = FALSE, zero_tol = 1e-16) {
    .Call(`_robClus_tclust_c1`, x, k, alpha, restrC, deterC, restr_fact, cshape, niter1, opt, equal_weights, zero_tol)
}

#' Internal function for concentration steps (refinement) in tclust2
#' @name tclust_c2
#' @param x Rcpp::NumericMatrix, The input data.
#' @param k The number of clusters initially searched for.
#' @param cluster arma::uvec A numerical vector of size \code{n} containing the 
#'      cluster assignment for each observation. Cluster names are integer numbers 
#'      from 1 to k, 0 indicates trimmed observations. Note that it could be empty 
#'      clusters with no observations when \code{equal_weights=FALSE}.
#' @param alpha double, The proportion of observations to be trimmed.
#' @param restrC Restriction type (0 for restriction on eigenvalues or determinant)
#' @param deterC Restriction on determinants (true or false)
#' @param restr_fact The constant \code{restr_fact >= 1} constrains the allowed 
#'  differences among group scatters in terms of eigenvalues ratio. Larger values 
#'  imply larger differences of group scatters, a value of 1 specifies the 
#'  strongest restriction.
#' @param cshape Shape constraint
#' @param niter2 The maximum number of concentration steps to be performed for the 
#'  \code{nkeep} solutions kept for further iteration. The concentration steps are 
#'  stopped, whenever two consecutive steps lead to the same data partition.
#' @param opt Define the target function to be optimized. A classification likelihood 
#'  target function is considered if \code{opt="HARD"} and a mixture classification 
#'  likelihood if \code{opt="MIXT"}.
#' @param equal_weights A logical value, specifying whether equal cluster weights 
#'  shall be considered in the concentration and assignment steps.
#' @param zero_tol The zero tolerance used. By default set to 1e-16.
#' @export
tclust_c2 <- function(x, k, cluster, alpha = 0.05, restrC = 0L, deterC = FALSE, restr_fact = 12, cshape = 1e10, niter2 = 20L, opt = "HARD", equal_weights = FALSE, zero_tol = 1e-16) {
    .Call(`_robClus_tclust_c2`, x, k, cluster, alpha, restrC, deterC, restr_fact, cshape, niter2, opt, equal_weights, zero_tol)
}

tclust_restr2_eigenv <- function(autovalues, ni_ini, factor_e = 12, zero_tol = 1e-16) {
    .Call(`_robClus_tclust_restr2_eigenv`, autovalues, ni_ini, factor_e, zero_tol)
}

tclust_restr2_deter_old <- function(autovalues, ni_ini, factor_e = 12, zero_tol = 1e-16) {
    .Call(`_robClus_tclust_restr2_deter_old`, autovalues, ni_ini, factor_e, zero_tol)
}

tclust_restr2_deter <- function(autovalues, ni_ini, restr_factor = 12, cshape = 1e10, zero_tol = 1e-16) {
    .Call(`_robClus_tclust_restr2_deter`, autovalues, ni_ini, restr_factor, cshape, zero_tol)
}

tclust_HandleSmallEv <- function(autovalues, zero_tol = 1e-16) {
    .Call(`_robClus_tclust_HandleSmallEv`, autovalues, zero_tol)
}

#' Internal function for concentration steps (initializations) in tkmeans2
#' @name tkmeans_c1
#' @param x Rcpp::NumericMatrix, The input data.
#' @param k The number of clusters initially searched for.
#' @param alpha double, The proportion of observations to be trimmed.
#' @param niter1 int, The number of concentration steps to be performed for the 
#'     nstart initializations. 
#' @param zero_tol The zero tolerance used. By default set to 1e-16.
#' @param points Optional initial mean vectors, \code{NULL} or a matrix with \code{k} 
#'  vectors used as means to initialize the algorithm. If initial mean vectors are 
#'  specified, \code{nstart} should be 1 (otherwise the same initial means are 
#'  used for all runs).
#' @export
tkmeans_c1 <- function(x, k, alpha = 0.05, niter1 = 3L, zero_tol = 1e-16, points = NULL) {
    .Call(`_robClus_tkmeans_c1`, x, k, alpha, niter1, zero_tol, points)
}

#' Internal function for concentration steps (refinement) in tkmeans2
#' @name tkmeans_c2
#' @param x Rcpp::NumericMatrix, The input data.
#' @param k The number of clusters initially searched for.
#' @param cluster arma::uvec A numerical vector of size \code{n} containing the 
#'      cluster assignment for each observation. Cluster names are integer numbers 
#'      from 1 to k, 0 indicates trimmed observations. 
#' @param alpha double, The proportion of observations to be trimmed.
#' @param niter2 The maximum number of concentration steps to be performed for the 
#'  \code{nkeep} solutions kept for further iteration. The concentration steps are 
#'  stopped, whenever two consecutive steps lead to the same data partition.
#' @param zero_tol The zero tolerance used. By default set to 1e-16.
#' @export
tkmeans_c2 <- function(x, k, cluster, alpha = 0.05, niter2 = 20L, zero_tol = 1e-16) {
    .Call(`_robClus_tkmeans_c2`, x, k, cluster, alpha, niter2, zero_tol)
}

